"""
notification_service — The single owner of notifications and the system tray.

Consolidates `ui/notification_manager.py`. Four audited problems are addressed:

**Notifications that never dismiss.** Every notification now has a deterministic
lifecycle owned by this service: it is shown, a single owned QTimer retires it,
and retirement also happens if the user closes it or the service stops. A
dismissal timer can no longer be orphaned by a widget being destroyed, because
no widget owns one.

**Notifications that overwrite each other.** There used to be one card, and a
notification arriving while another was up replaced its text. Anyone who had
not closed the first never saw that a second had come: the card was already
there, in the same place, and only its words had changed. Each notification
now gets its own card, stacked above the ones still up, for its own thirty
seconds. There is still exactly one timer -- it is armed for whichever card is
due to go next.

**Notification storms.** Going offline and online repeatedly used to emit a
toast per transition, per subscriber. Notifications are now de-duplicated by
key within a cool-off window and rate-limited overall, so network flapping
produces one message rather than a burst.

**Unprofessional Windows identity.** Windows derives the name and icon shown on
a toast from the process's Application User Model ID. Without an explicit one,
it falls back to an autogenerated identifier (typically the interpreter), which
is what the screenshots showed. `SetCurrentProcessExplicitAppUserModelID` is
set here before any tray icon is created.

**Duplicate / lost tray icons.** The tray icon is created once, owned by this
service, and its availability is checked and logged rather than silently
assumed. If the platform has no tray, notifications degrade to logging instead
of disabling the application.
"""
from __future__ import annotations

import sys
import threading
import time
from typing import Dict, List, Optional

from PySide6.QtCore import QObject, QThread, QTimer, QUrl, Qt, Signal
from PySide6.QtGui import (
    QAction, QColor, QDesktopServices, QFont, QIcon, QPainter, QPixmap,
    QRadialGradient,
)
from PySide6.QtWidgets import QApplication, QMenu, QSystemTrayIcon

from core.service import BaseService

from .toast_popup import ToastPopup

#: Stable identity for Windows toast attribution.
APP_USER_MODEL_ID = "Monitra"


class NotificationLevel:
    INFO = "info"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"


_LEVEL_ICONS = {
    NotificationLevel.INFO: QSystemTrayIcon.MessageIcon.Information,
    NotificationLevel.SUCCESS: QSystemTrayIcon.MessageIcon.Information,
    NotificationLevel.WARNING: QSystemTrayIcon.MessageIcon.Warning,
    NotificationLevel.ERROR: QSystemTrayIcon.MessageIcon.Critical,
}


#: Base size the artwork is defined at. There is exactly one definition of
#: the mark (core/branding.py) and every size is rendered from it, so the
#: tray icon, the window icon, the .ico export and the sidebar can never
#: drift apart -- and dropping a real logo file into desktop/assets/
#: replaces all of them at once.
_ICON_BASE_SIZE = 64


def _paint_app_icon(size: int) -> QPixmap:
    """The Monitra mark at `size`, from the one shared definition.

    Falls back to the legacy hand-painted glyph only if rendering the mark
    somehow produces nothing, so a broken or missing asset can never leave
    the tray with no icon at all.
    """
    from core.branding import logo_pixmap

    pixmap = logo_pixmap(size)
    if not pixmap.isNull():
        return pixmap
    return _paint_legacy_app_icon(size)


def _paint_legacy_app_icon(size: int) -> QPixmap:
    from PySide6.QtGui import QLinearGradient, QPainterPath, QPen, QBrush

    pixmap = QPixmap(size, size)
    pixmap.fill(Qt.GlobalColor.transparent)

    painter = QPainter(pixmap)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    painter.scale(size / _ICON_BASE_SIZE, size / _ICON_BASE_SIZE)

    # 1. Linear Gradient: Cyan/Blue (#38BDF8 -> #3B82F6) to Purple (#8B5CF6)
    gradient = QLinearGradient(0, 0, 64, 64)
    gradient.setColorAt(0.0, QColor("#38BDF8"))
    gradient.setColorAt(0.4, QColor("#3B82F6"))
    gradient.setColorAt(1.0, QColor("#8B5CF6"))

    # 2. Outer Ring / Arc (Thick gradient stroke, open on right)
    pen_ring = QPen(QBrush(gradient), 6)
    pen_ring.setCapStyle(Qt.PenCapStyle.RoundCap)
    painter.setPen(pen_ring)
    painter.setBrush(Qt.BrushStyle.NoBrush)
    painter.drawArc(6, 6, 52, 52, -40 * 16, 340 * 16)

    # 3. Bold Centered Checkmark
    check_path = QPainterPath()
    check_path.moveTo(22, 32)
    check_path.lineTo(30, 41)
    check_path.lineTo(44, 23)

    pen_check = QPen(QBrush(gradient), 6)
    pen_check.setCapStyle(Qt.PenCapStyle.RoundCap)
    pen_check.setJoinStyle(Qt.PenJoinStyle.RoundJoin)
    painter.setPen(pen_check)
    painter.drawPath(check_path)

    painter.end()
    return pixmap


def create_app_icon(sizes: Optional[list] = None) -> QIcon:
    """Build the Monitra application icon from the shared brand mark. Pass `sizes` (e.g. for a build-time .ico export) to get a single
    QIcon carrying one crisp pixmap per size instead of one scaled-up
    bitmap; every existing caller keeps today's single-size behavior."""
    icon = QIcon()
    for size in (sizes or [_ICON_BASE_SIZE]):
        icon.addPixmap(_paint_app_icon(size))
    return icon


def set_windows_app_identity() -> None:
    """
    Declare an explicit Application User Model ID.

    Must run before the first tray icon is created. Without it, Windows
    attributes toasts to an autogenerated identifier rather than to Monitra.
    """
    if sys.platform != "win32":  # pragma: no cover - platform specific
        return
    try:
        import ctypes

        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(APP_USER_MODEL_ID)
    except Exception:  # noqa: BLE001
        # Cosmetic only; never block startup for it.
        pass


class _ShownCard:
    """One notification that is on screen: its card and when it goes."""

    __slots__ = ("card", "key", "title", "message", "link", "deadline")

    def __init__(self, card, key, title, message, link, deadline) -> None:
        self.card = card
        self.key = key
        self.title = title
        self.message = message
        #: URL this card opens when clicked, or None. Held per card, so a
        #: click can only ever open the link of the card that was clicked.
        self.link = link
        #: `time.monotonic()` at which the card is retired.
        self.deadline = deadline


class NotificationService(BaseService):
    """
    Owns notification delivery and the system tray icon.

    Signals:
        restore_requested() — user asked to bring the window back
        quit_requested()    — user asked to quit from the tray menu
    """

    name = "notifications"

    restore_requested = Signal()
    quit_requested = Signal()
    toast_requested = Signal(str, str, str, str, str)  # message, level, title, link, key

    #: A repeat of the same key inside this window is suppressed.
    DEDUPE_SECONDS = 2.0
    #: Ceiling on notifications shown per minute, whatever their key.
    MAX_PER_MINUTE = 30
    #: How long a notification stays on screen before it is retired.
    #:
    #: Every notification is drawn by `ToastPopup`, a window this application
    #: owns, precisely so that this number means something. Passed to the
    #: platform's own toast it does not: `Shell_NotifyIcon`'s `uTimeout` has
    #: been ignored since Vista, and the real on-screen time comes from the
    #: user's accessibility setting (Settings -> Accessibility -> Visual
    #: effects -> "Dismiss notifications after this amount of time"), which is
    #: five seconds by default and about twenty-five for a long toast. That is
    #: why the platform toast is now only the fallback for a machine the popup
    #: cannot be placed on.
    #:
    #: Thirty seconds, for every notification. It was a minute; the owner
    #: asked for half that (2026-09-30) -- long enough to be read by someone
    #: who looked away, short enough that the card is not still sitting in
    #: the corner of the screen when the next thing happens.
    DISPLAY_MS = 30_000

    #: The most cards on screen at once. A notification that would make one
    #: more retires the oldest: a column of cards up the side of the screen
    #: is not something anybody reads, and the oldest has had the longest.
    MAX_CARDS = 4
    #: Gap between one card and the next above it, in pixels.
    CARD_GAP = 10

    def __init__(self, runtime, parent: Optional[QObject] = None) -> None:
        super().__init__(runtime, parent)
        self._tray: Optional[QSystemTrayIcon] = None
        self._menu: Optional[QMenu] = None
        self._icon: Optional[QIcon] = None
        self._recent: Dict[str, float] = {}
        self._shown_times: list = []
        # Admission state is read and written by whichever thread calls
        # notify(); the tray itself is only ever touched on this object's own
        # thread (see `_deliver`).
        self._admit_lock = threading.Lock()
        # One owned timer retires every notification. Single instance, single
        # owner: a dismissal timer can never be orphaned. With several cards
        # up it is armed for whichever goes next, and re-armed as each one
        # does -- there is never a timer per card.
        #
        # Precise, because it is what takes a card down: Qt rounds a coarse
        # timer this long to whole seconds and may fire it early, and a card
        # asked to stay for thirty seconds should stay for thirty.
        self._dismiss_timer = QTimer(self)
        self._dismiss_timer.setSingleShot(True)
        self._dismiss_timer.setTimerType(Qt.TimerType.PreciseTimer)
        self._dismiss_timer.timeout.connect(self._on_dismiss_timeout)
        #: The deadline the timer is currently armed for, so a timeout retires
        #: what it was set for even if it lands a few milliseconds early.
        self._armed_deadline: Optional[float] = None
        self._available = False
        #: The notifications on screen, oldest first -- which is bottom first:
        #: a new card is stacked above the ones already up. Each card is a
        #: window this application draws, the only surface that can honour
        #: `DISPLAY_MS`; the platform toast is the fallback for a machine a
        #: card cannot be shown on. Cards own no timer.
        self._cards: List[_ShownCard] = []
        #: Cards not currently showing anything, kept to be used again rather
        #: than destroying and recreating a window per notification.
        self._spare_cards: List[ToastPopup] = []
        #: The card most recently shown, whether or not it is still up.
        self._last_card: Optional[ToastPopup] = None
        #: Cleared for good if the popup cannot be built, so a platform that
        #: refuses it falls back once rather than on every notification.
        self._popup_enabled = True
        #: URL the *platform toast* opens when it is clicked, or None. A
        #: platform toast renders plain text, so a URL in the body is not a
        #: link and cannot be clicked; without this a notification that exists
        #: to point somewhere is a dead end — the user clicks it, it
        #: dismisses, and the address is gone. (A card carries its own link.)
        #:
        #: Exactly one is held, replaced when the toast is superseded and
        #: cleared when it is retired, so a click can never open the link of
        #: a notification that is no longer on screen.
        self._pending_link: Optional[str] = None
        #: When the platform toast's lifecycle ends, or None if none is up.
        self._toast_deadline: Optional[float] = None
        # A queued connection to self: whatever thread emits this signal, the
        # slot runs on the thread this service lives on (the GUI thread). It
        # is what makes notify() safe to call from anywhere -- see notify().
        self.toast_requested.connect(
            self._deliver, Qt.ConnectionType.QueuedConnection
        )

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def on_start(self) -> None:
        set_windows_app_identity()

        self._available = QSystemTrayIcon.isSystemTrayAvailable()
        if not self._available:
            # Not fatal. The audit found tray failures silently disabling
            # application behaviour; here it is logged and the app continues.
            self.log.warning(
                "no system tray available; notifications will be logged only"
            )
            return

        self._icon = create_app_icon()
        self._tray = QSystemTrayIcon(self._icon, self)
        self._tray.setToolTip("Monitra — Staff Management")
        self._tray.activated.connect(self._on_tray_activated)
        self._tray.messageClicked.connect(self._on_message_clicked)

        self._menu = QMenu()
        restore = QAction("Open Monitra", self)
        restore.triggered.connect(self.restore_requested.emit)
        self._menu.addAction(restore)
        self._menu.addSeparator()
        quit_action = QAction("Quit Monitra", self)
        quit_action.triggered.connect(self.quit_requested.emit)
        self._menu.addAction(quit_action)
        self._tray.setContextMenu(self._menu)

        self._tray.show()
        self.log.info("system tray initialised")

    def on_stop(self, timeout_ms: int) -> bool:
        self._retire_current()
        for card in self._spare_cards:
            card.deleteLater()
        self._spare_cards = []
        self._last_card = None
        if self._tray is not None:
            self._tray.hide()
            self._tray.setContextMenu(None)
        if self._menu is not None:
            self._menu.deleteLater()
            self._menu = None
        self._tray = None
        return True

    @property
    def tray(self) -> Optional[QSystemTrayIcon]:
        """The tray icon, for callers that need to attach window behaviour."""
        return self._tray

    def _on_tray_activated(self, reason) -> None:
        if reason in (
            QSystemTrayIcon.ActivationReason.Trigger,
            QSystemTrayIcon.ActivationReason.DoubleClick,
        ):
            self.restore_requested.emit()

    def _on_message_clicked(self) -> None:
        """The user clicked the toast itself.

        If it carried a link, open it in the user's browser; otherwise fall
        back to bringing the window back, which is what a click on a message
        with nowhere else to go should do. Runs on the GUI thread — Qt
        delivers `messageClicked` on the thread the tray lives on.
        """
        link, self._pending_link = self._pending_link, None
        self._open_link_or_restore(link)

    def _open_link_or_restore(self, link: Optional[str]) -> None:
        """What a click on a notification does, whichever surface showed it."""
        if not link:
            self.restore_requested.emit()
            return
        self.log.info("notification clicked; opening %s", link)
        try:
            QDesktopServices.openUrl(QUrl(link))
        except Exception:  # noqa: BLE001
            # Cosmetic: a browser that will not launch must never take the
            # application down with it.
            self.log.exception("could not open %s", link)

    # ── Delivery ──────────────────────────────────────────────────────────────

    def _admit(self, key: str) -> bool:
        """Apply de-duplication and rate limiting. True if the message may show."""
        now = time.monotonic()

        with self._admit_lock:
            last = self._recent.get(key)
            if last is not None and now - last < self.DEDUPE_SECONDS:
                self.log.debug("suppressed duplicate notification %r", key)
                return False

            self._shown_times = [t for t in self._shown_times if now - t < 60.0]
            if len(self._shown_times) >= self.MAX_PER_MINUTE:
                self.log.info("notification rate limit reached; suppressing %r", key)
                return False

            self._recent[key] = now
            self._shown_times.append(now)
            # Keep the dedupe map from growing without bound over a long session.
            if len(self._recent) > 64:
                cutoff = now - self.DEDUPE_SECONDS
                self._recent = {k: t for k, t in self._recent.items() if t >= cutoff}
        return True

    @property
    def _popup(self) -> Optional[ToastPopup]:
        """The newest card: the one on top of the stack, or, with nothing up,
        the one shown last. None before the first notification and after the
        service stops."""
        return self._cards[-1].card if self._cards else self._last_card

    # ── The stack of cards ────────────────────────────────────────────────────

    def _clock(self) -> float:
        return time.monotonic()

    def _arm_timer(self) -> None:
        """Arm the one timer for whichever notification goes next."""
        deadlines = [shown.deadline for shown in self._cards]
        if self._toast_deadline is not None:
            deadlines.append(self._toast_deadline)
        if not deadlines:
            self._dismiss_timer.stop()
            self._armed_deadline = None
            return
        self._armed_deadline = min(deadlines)
        remaining_ms = round((self._armed_deadline - self._clock()) * 1000)
        self._dismiss_timer.start(max(0, remaining_ms))

    def _on_dismiss_timeout(self) -> None:
        """The timer fired: retire what it was armed for, and anything else
        that is due, then arm it for the next."""
        due = self._clock()
        if self._armed_deadline is not None:
            due = max(due, self._armed_deadline)
        due += 0.05     # two cards shown in the same instant go together
        for shown in [entry for entry in self._cards if entry.deadline <= due]:
            self._retire_card(shown, restack=False)
        if self._toast_deadline is not None and self._toast_deadline <= due:
            self._retire_toast()
        self._restack()
        self._arm_timer()

    def _retire_card(self, shown: _ShownCard, restack: bool = True) -> None:
        """Take one card down and put it back with the spares."""
        if shown not in self._cards:
            return
        self._cards.remove(shown)
        shown.card.hide()
        self._spare_cards.append(shown.card)
        self.log.debug("notification retired (%s)", shown.key)
        if restack:
            self._restack()

    def _retire_toast(self) -> None:
        """End the platform toast's lifecycle.

        The platform dismisses its own toast. This is the service's own
        end-of-life marker for it: its link must go with it, because a click
        arriving afterwards belongs to no notification and must not open a
        stale address.
        """
        self._pending_link = None
        self._toast_deadline = None

    def _retire_current(self) -> None:
        """End every notification that is up, cards and platform toast alike."""
        for shown in list(self._cards):
            self._retire_card(shown, restack=False)
        self._retire_toast()
        self._arm_timer()

    def _restack(self) -> None:
        """Sit each card on the one below it, oldest at the corner.

        Run whenever the stack changes, so a card whose neighbour below has
        gone slides down into the space. Then the cards are raised from the
        top of the stack down, leaving the lowest one frontmost: each card's
        window is larger than the card by the margin its shadow is painted
        in, and with the newest frontmost that margin lay over the close
        button of the card beneath it.
        """
        lift = 0
        for shown in self._cards:
            shown.card.place(lift)
            lift += shown.card.card_height() + self.CARD_GAP
        for shown in reversed(self._cards):
            # Not `raise_()`: on macOS that activates the application, so every
            # card appearing or closing would pull Monitra in front of
            # whatever the user was typing in. See ToastPopup.bring_to_front.
            shown.card.bring_to_front()

    def _entry_for(self, card: ToastPopup) -> Optional[_ShownCard]:
        return next((shown for shown in self._cards if shown.card is card), None)

    def _on_card_clicked(self, card: ToastPopup) -> None:
        """A click on a card is a click on that notification: open its link,
        or bring the window back if it has none, and take the card down."""
        shown = self._entry_for(card)
        if shown is None:
            return
        link = shown.link
        self._retire_card(shown)
        self._arm_timer()
        self._open_link_or_restore(link)

    def _on_card_dismissed(self, card: ToastPopup) -> None:
        """The user closed a card with its close button: that card goes, the
        others stay, and the timer moves on to whichever is next."""
        shown = self._entry_for(card)
        if shown is None:
            return
        self._retire_card(shown)
        self._arm_timer()

    def _ensure_popup(self) -> Optional[ToastPopup]:
        """A card ready to show a notification, or None if one cannot be built.

        A spare one if there is one, otherwise a new window. It stays with
        the spares until `_show_card` takes it.

        Runs on this service's own thread — the GUI thread — because every
        caller is `_deliver`, which the queued `toast_requested` connection
        already placed there.
        """
        if not self._popup_enabled:
            return None
        if self._spare_cards:
            return self._spare_cards[-1]
        if QApplication.instance() is None:
            # Nothing to parent a window to. Not an error: a headless run
            # still logs, and the tray fallback still applies.
            return None
        try:
            popup = ToastPopup()
        except Exception:  # noqa: BLE001
            # A window that cannot be built is not a reason to lose the
            # notification — fall back to the platform toast from here on.
            self.log.exception("could not create the notification popup")
            self._popup_enabled = False
            return None
        popup.clicked.connect(lambda card=popup: self._on_card_clicked(card))
        popup.dismissed.connect(lambda card=popup: self._on_card_dismissed(card))
        self._spare_cards.append(popup)
        return popup

    def _show_card(self, title: str, message: str, level: str, link: str, key: str) -> bool:
        """Put this notification on a card of its own, above the ones up.

        :return: False if no card could be shown, and the caller should fall
            back to the platform toast.
        """
        # The very same notification, still on screen: nothing new to say, so
        # no second card saying it. Its time starts again.
        for shown in self._cards:
            if shown.key == key and shown.title == title and shown.message == message:
                shown.deadline = self._clock() + self.DISPLAY_MS / 1000.0
                shown.link = link or None
                return True

        card = self._ensure_popup()
        if card is None:
            return False
        lift = sum(entry.card.card_height() + self.CARD_GAP for entry in self._cards)
        try:
            presented = card.present(title, message, level, lift)
        except Exception:  # noqa: BLE001
            self.log.exception("failed to show the notification popup")
            presented = False
        if not presented:
            return False

        # Counted from now, with the card on screen -- not from before it
        # was built and laid out, which for the first card is real time.
        deadline = self._clock() + self.DISPLAY_MS / 1000.0
        self._spare_cards.remove(card)
        self._cards.append(_ShownCard(card, key, title, message, link or None, deadline))
        self._last_card = card
        # Too many, or too tall for the screen: the oldest makes room. The
        # newest is never the one to go -- it is the one nobody has seen.
        while len(self._cards) > 1 and (
            len(self._cards) > self.MAX_CARDS or getattr(card, "clipped", False)
        ):
            self._retire_card(self._cards[0], restack=False)
            self._restack()
        self._restack()
        return True

    def notify(
        self,
        message: str,
        level: str = NotificationLevel.INFO,
        title: str = "Monitra",
        key: Optional[str] = None,
        link: Optional[str] = None,
    ) -> bool:
        """
        Show a notification.

        Safe to call from any thread. Admission control runs on the calling
        thread; the tray itself is only ever touched on the thread this
        service lives on, by hopping through a queued signal. Every caller
        today is already on the GUI thread, but nothing in the type system
        said so, and a single background service reaching in here directly
        would have been a widget mutated from a worker thread.

        :param key: De-duplication key; defaults to the message text. Callers
            that emit the same message for different reasons should pass a key
            so throttling behaves sensibly.
        :param link: URL the toast opens when the user clicks it. A platform
            toast shows plain text, so a URL written into `message` is not
            clickable — pass it here as well for a notification whose whole
            purpose is to send the user somewhere.
        :return: True if it was displayed (in-app card or platform toast), or
            handed to the GUI thread to display. False if it was suppressed,
            or no display surface was available at all.
        """
        dedupe_key = key or f"{level}:{message}"
        if not self._admit(dedupe_key):
            return False

        self.log.info("notify [%s] %s", level, message)

        if QThread.currentThread() is not self.thread():
            self.toast_requested.emit(message, level, title, link or "", dedupe_key)
            return True

        return self._deliver(message, level, title, link or "", dedupe_key)

    def _deliver(
        self, message: str, level: str, title: str, link: str = "", key: str = ""
    ) -> bool:
        """Show an admitted notification. Runs on this service's own thread.

        The in-app card is a plain widget and needs no system tray, so it is
        tried unconditionally; only the platform-toast fallback below needs
        `_available`/`_tray`. A missing tray must degrade to logging, per this
        module's docstring — not drop every notification, including a failed
        task creation, with no feedback at all.
        """
        # A card of its own first, because a card is the only surface that
        # stays up for `DISPLAY_MS`. The platform toast is shown only if a
        # card could not be — never both, or one event would notify the user
        # twice.
        if self._show_card(title, message, level, link, key or f"{level}:{message}"):
            self._arm_timer()
            return True

        if not self._available or self._tray is None:
            return False
        # Set before showing: on a fast click the platform can deliver
        # `messageClicked` the instant the toast appears.
        self._pending_link = link or None
        try:
            # Use Monitra brand QIcon so Windows system toast displays Monitra logo
            tray_icon = self._icon if self._icon and not self._icon.isNull() else _LEVEL_ICONS.get(level, QSystemTrayIcon.MessageIcon.Information)
            self._tray.showMessage(
                title, message, tray_icon,
                self.DISPLAY_MS,
            )
        except Exception:  # noqa: BLE001
            self.log.exception("failed to display notification")
            self._pending_link = None
            return False

        # The platform toast dismisses itself; the timer only ends its
        # lifecycle (and its link), and is given a margin so it cannot end it
        # while the toast is still up. A card gets the display time exactly.
        self._toast_deadline = self._clock() + (self.DISPLAY_MS + 500) / 1000.0
        self._arm_timer()
        return True

    # ── Convenience wrappers (compatible with the previous manager) ───────────

    def show_info(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.INFO, title, key)

    def show_success(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.SUCCESS, title, key)

    def show_warning(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.WARNING, title, key)

    def show_error(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.ERROR, title, key)
